filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log   # 호스트 /var/log 에 있는 로그 수집 예시

output.logstash:
  hosts: ["logstash:5044"]
  username: "elastic"
  password: "qwer1234"

setup.kibana:
  host: "kibana:5601"
